version: 0.2
phases:
 install:
   commands:
     - echo "install step"
     - npm i
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - ng build --prod
 post_build:
   commands:
     - echo "post_build step"