version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "homedashapps.com"
        BUILD_ENV: "prod"
phases:
 install:
   commands:
     - echo "install step"
     - npm i -g @angular/cli
     - npm i
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - ng build --${BUILD_ENV}
 post_build:
   commands:
     - echo "post_build step"
     - aws s3 rm s3://${S3_BUCKET} --recursive
     - aws s3 cp dist s3://${S3_BUCKET} --recursive 